### ISSUE TITLE
Feature request: add options to allow static addressing

### ISSUE THREAD

**Issue by tklicki** [debops/ansible-tinc#34]
Hi,
I think it would be useful to manualy set IP address to every host in the mesh network. I'm thinking about something like this - part of host_vars:

```
tinc__networks:
  (...)
  link_type: static_ip
    - address: 1.2.3.4
    - netmask: 24
  (...)
```

Right now as I understand it is not possible. What do you think about this idea?

**Comment by le9i0nx** [comment]
use https://github.com/debops/ansible-ifupdown
or 

``` yaml
tinc__network_mesh_pve:
  name: '{{ tinc__interface_mesh_pve }}'
  interface: '{{ tinc__interface_mesh_pve }}'
  hwaddr: ''
  bridge: ''
  link_type: 'static'
  boot: True
  port: '655'
  mlock: True
  chroot: True
  allow: ''
  user: '{{ tinc__user }}'
  tinc_exclude_addresses: '{{ tinc__exclude_addresses_mesh0 }}'
  tinc_options:
    Mode: 'switch'
    DeviceType: 'tap'
    Cipher: 'aes-256-cbc'
    Digest: 'SHA512'
    ConnectTo: '{{ tinc__connect_to_mesh_pve }}'

tinc__ifupdown_interface:
  - iface: '{{ tinc__interface_mesh_pve }}'
    type: 'interface'
    inet: 'static'
    auto: True
    addresses: '{{ tinc_host_addr }}'
tinc_host_addr: [ '172.17.35.32/24' ]
```

https://github.com/le9i0nx/ansible-root/blob/master/group_vars/pve.yml#L29
https://github.com/le9i0nx/ansible-root/blob/master/service/tinc.yml
https://github.com/le9i0nx/ansible-networkd
